class System:
    def is_song_playing(self) -> bool:
        ...

    def get_song_name(self) -> str:
        ...

    def get_song_album(self) -> str:
        ...

    def get_song_artists(self) -> list[str]:
        ...

    def get_song_length(self) -> float:
        ...

    def get_song_pos(self) -> float:
        ...